### ISSUE TITLE
Add authentication to application

### ISSUE THREAD

**Issue by tfadeyi** [comp6239/Personal-tutor-finder-app#2]
Using Firebase auth features to bring authentication to the application, currently only via email and password.

Sign Up: new users should be forced to choose items from the list of subject
Sign In
Forget Password

**Comment by Cecish** [comment]
Unable to sign in using the credentials in the README file.

Error encoutered:
`2019-04-05 11:18:47.168 12303-12303/com.example.toto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toto, PID: 12303
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.example.toto.users.Role.toString()' on a null object reference
        at com.example.toto.users.User.marshal(User.java:75)
        at com.example.toto.users.UserDatabaseHelper.upsert(UserDatabaseHelper.java:21)
        at com.example.toto.users.UserController$1.onComplete(UserController.java:40)
        at com.google.android.gms.tasks.zzj.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by tfadeyi** [comment]
hey @Cecish when you have some time could you give another look at branch #7 ? Are you cool with the design and code? I've attached the UML diagram of the module. 
![User_pkg](https://user-images.githubusercontent.com/16049411/55820944-2b827200-5af4-11e9-9be2-a928c19fe9a3.png)

**Comment by tfadeyi** [comment]
The user model is not final, the list of subject can also be added

**Comment by tfadeyi** [comment]
Sessions and subjects present in the user model are also initialized during sign in and sign up
