### ISSUE TITLE
Transition between the signinsignup activity is buggy

### ISSUE THREAD

**Issue by Cecish** [comp6239/Personal-tutor-finder-app#34]
It fails sometimes (when testing on my phone but the logs are not printed on my console)
The transition is not right (it's like the app closes and reopens with the home activity on successfull sign in/up).

What I have done in the not_working_properly_version (cf. line 174 in SignInSignUp.java): 
Just before going to the main activity for successfully logged-in students/tutors, their profile picture is downloaded from Firestore (if any) and the user's profile_picture attribute is set with this picture.

**Comment by Cecish** [comment]
When it fails (which is not always):
```
2019-04-24 00:37:28.464 21808-21808/com.example.toto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toto, PID: 21808
    java.lang.IllegalStateException: Fragment PlaceholderFragment{146ca36} not attached to Activity
        at android.support.v4.app.Fragment.startActivity(Fragment.java:1082)
        at android.support.v4.app.Fragment.startActivity(Fragment.java:1073)
        at com.example.toto.SignInSignUp$PlaceholderFragment.startStudentMainActivity(SignInSignUp.java:361)
        at com.example.toto.SignInSignUp$PlaceholderFragment.startStudentorTutorMainActivity(SignInSignUp.java:375)
        at com.example.toto.SignInSignUp$PlaceholderFragment.access$300(SignInSignUp.java:153)
        at com.example.toto.SignInSignUp$PlaceholderFragment$1$2.onSuccess(SignInSignUp.java:180)
        at com.example.toto.SignInSignUp$PlaceholderFragment$1$2.onSuccess(SignInSignUp.java:175)
        at com.google.android.gms.tasks.zzn.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Cecish** [comment]
I have been able to solve it, by using an oncomplete listener instead of onsuccess and onfailure listeners. I will clean my code a bit and push
