### ISSUE TITLE
Exception when iteration over subjects in User

### ISSUE THREAD

**Issue by Cecish** [comp6239/Personal-tutor-finder-app#35]
In the not_working_properly_version branch, in User.java:
- when the user logged in is associated with subjects (such as "oluwole2020")
- when calling getOrderedSubjects()

```
2019-04-24 00:45:33.872 22157-22157/com.example.toto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toto, PID: 22157
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.toto/com.example.toto.users.UserProfileActivity}: java.lang.ClassCastException: java.util.HashMap cannot be cast to com.example.toto.subjects.Subject
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
     Caused by: java.lang.ClassCastException: java.util.HashMap cannot be cast to com.example.toto.subjects.Subject
        at com.example.toto.users.User.getOrderedSubjects(User.java:140)
        at com.example.toto.users.UserProfileActivity.renderSubjects(UserProfileActivity.java:115)
        at com.example.toto.users.UserProfileActivity.onCreate(UserProfileActivity.java:50)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6119) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

**Comment by tfadeyi** [comment]
It was my fault, I made a mistake in initializing the User.

```
package com.example.toto.users;

import android.graphics.Bitmap;
import android.net.Uri;
import android.os.Parcel;
import android.os.Parcelable;
import android.support.annotation.NonNull;
import android.util.Log;

import com.example.toto.interfaces.Storable;
import com.example.toto.sessions.Status;
import com.example.toto.subjects.Subject;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.firestore.DocumentSnapshot;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Observable;

public class User extends Observable implements Storable, Parcelable {
    //combination of FirebaseUser and user from the `users` collection in firestore
    private String username;
    private String email;
    private Role role;
    private String id;
    private Bitmap profile_picture;
    private Status status; // for tutors
    private Map<String,Subject> subjects = new HashMap<>();


    public User(DocumentSnapshot user){
        id = user.getId();
        email = (String) user.getData().get("Email");
        username = (String) user.getData().get("Username");
        role = Role.valueOf((String)user.getData().get("Role"));
        if (role.equals(Role.TUTOR))
            status = Status.valueOf((String)user.getData().get("Status"));
        subjects = flatten2((Map<String, Map<String, Object>>) user.getData().get("Subjects"));
        if (subjects == null)
            subjects = new HashMap<>();
    }

    public User(String username,String email, Role role,String id, Status status){
        this.username = username;
        this.email = email;
        this.id = id;
        this.role = role;
        this.status = status;
    }

    //Only used at signIn and signUp time
    public User(FirebaseUser user){
        id = user.getUid();
        email = user.getEmail();
        username = user.getDisplayName();
    }

    public void setEmail(String email) {
        this.email = email;
        setChanged();
    }

    public void setRole(Role role) {
        this.role = role;
        setChanged();
    }

    public void setUsername(String username) {
        this.username = username;
        setChanged();
    }

    public void setStatus(Status status) {
        this.status = status;
        setChanged();
    }

    public void setSubjects(Map<String, Subject> subjects) {
        this.subjects = subjects;
    }

    public void addSubject(Subject s){
        if (!subjects.containsKey(s.getId())){
            subjects.put(s.getId(),s);
            setChanged();
        }
    }

    public void removeSubject(Subject s){
        if (subjects.containsKey(s.getId())){
            subjects.remove(s.getId());
            setChanged();
        }
    }

    public Role getRole() {
        return role;
    }

    public String getEmail() {
        return email;
    }

    public String getId() {
        return id;
    }

    public Bitmap getProfile_picture() {
        return profile_picture;
    }

    public void setProfile_picture(Bitmap profile_picture) {
        this.profile_picture = profile_picture;
    }

    public String getUsername() {
        return username;
    }

    public Status getStatus() {
        return status;
    }

    public Map<String, Subject> getSubjects() {
        return subjects;
    }

    /**
     * Return the alphabetically ordered list of the subjects a student (tutor) wishes to learn (teach)
     * @return alphabetically ordered list of the subjects a student (tutor) wishes to learn (teach)
     */
    public List<String> getOrderedSubjects() {
        List<String> res = new ArrayList<>();

        //Iterate over map values only (no need of the associated keys here)
        for (Subject subject_item: subjects.values()) {
            res.add(subject_item.getName());
        }

        //Sorting the list of subjects' name by alphabetical order (case sensitive)
        Collections.sort(res, new Comparator<String>() {
            @Override
            public int compare(String s1, String s2) {
                return s1.compareTo(s2);
            }
        });

        return res;
    }

    public Map<String, Object> marshal(){
        //the Id must be fetch from the instance, in firestore document ids aren't in the map
        Map<String, Object> user = new HashMap<>();
        user.put("Username",username);
        user.put("Email",email);
        user.put("Role",role.toString());
        if (role.equals(Role.TUTOR))
            user.put("Status", status.toString());
        user.put("Subjects",flatten(subjects));

        return user;
    }

    private Map<String,Object> flatten(Map<String,Subject> map){
        Map<String,Object> newMap = new HashMap<>();
        for(Map.Entry<String, Subject> entry : map.entrySet()) {
            newMap.put(entry.getKey(), ((Subject)entry.getValue()).marshal());
        }
        return newMap;
    }

    public Map<String,Subject> flatten2(Map<String,Map<String,Object>> map){
        Map<String,Subject> newMap = new HashMap<>();
        for(Map.Entry<String, Map<String,Object>> entry : map.entrySet()) {
            newMap.put(entry.getKey(), new Subject(entry.getKey(),(String) entry.getValue().get("Name")));
        }
        return newMap;
    }


    /**
     * describeContents method for a Parcelable class (in this project, such class(es) has(have) no
     * child classes)
     * @return 0. Parcelable class(es) in this project has(have) no child classes
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Write an object to a parcel
     * @param dest The Parcel in which the object should be written
     * @param flags Additional flags about how the object should be written
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.username);
        dest.writeString(this.email);
        dest.writeString(this.role.toString());
        dest.writeString(this.id);
        //dest.writeString(this.status.toString()); TODO instantiation to avoid null
    }

    /**
     * Regenerate the object from parcel
     */
    public static final Creator<User> CREATOR = new Creator<User>() {
        public User createFromParcel(Parcel in) {
            return new User(in);
        }

        public User[] newArray(int size) {
            return new User[size];
        }
    };

    /**
     * Constructor that takes a parcel and construct a populated user object
     * @param in parcel
     */
    private User(Parcel in) {
        username = in.readString();
        email = in.readString();
        role = Role.valueOf(in.readString());
        this.id = in.readString();
        //this.status = Status.valueOf(in.readString()); TODO instantiation to avoid null
    }
}
```

**Comment by tfadeyi** [comment]
I'll make a commit to master with this change

**Comment by Cecish** [comment]
It seems the subjects attribute in User is always empty even if the current user is associated with some subjects.

Example:
Test with the following user: DocumentSnapshot data: {Username=Cecile, Subjects={HkQvaWpQl5ghM1Bbwkx4={Name=Particle Physics}, PWqpOHEkaRlhFEUsoVDe={Name=Musicology}}, Role=STUDENT, Email=...}
String.valueOf(subjects) //Prints {}

**Comment by Cecish** [comment]
Also, when logging with a student/tutorwith no subjects:

```
2019-04-24 18:54:11.938 14417-14417/com.example.toto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.toto, PID: 14417
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
        at com.example.toto.users.User.flatten2(User.java:152)
        at com.example.toto.users.User.<init>(User.java:36)
        at com.example.toto.users.UserManager$1.onComplete(UserManager.java:52)
        at com.google.android.gms.tasks.zzj.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by tfadeyi** [comment]
```    //Transform the map of maps to a single map
    //if arg is null returns empty HashMap
    public Map<String,Subject> flatten2(Map<String,Map<String,Object>> map){
        //null check
        if (map==null){
            return new HashMap<>();
        }
        Map<String,Subject> newMap = new HashMap<>();
        for(Map.Entry<String, Map<String,Object>> entry : map.entrySet()) {
            newMap.put(entry.getKey(), new Subject(entry.getKey(),(String) entry.getValue().get("Name")));
        }
        return newMap;
    }
```
